#pragma once 

#include <opencv2/video/tracking.hpp>
#include <boost/dll/import.hpp>
#include <boost/tokenizer.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include <boost/property_tree/ini_parser.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/info_parser.hpp>
#include <boost/filesystem.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/clamp.hpp>
#include <iostream>
#include <vector>
#include <string>
#include <mutex>
#include <map>
#include <functional>
#include <set>
#include <random>