@ECHO OFF
SETLOCAL enableextensions
setlocal EnableDelayedExpansion
SET SOLUTION_DIR=%1
SET PLATFORM=%2
SET CONFIGURATION=%3

if not exist native\%PLATFORM% mkdir native\%PLATFORM%

COPY  %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Backend.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Core.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Simulator.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Loop.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Scheduler.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Initializer.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Reservoir.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\CPU.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\GPU.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Model.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Engine.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Local.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Network.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Remote.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\Distributed.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\ViewModel.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\TRN4CPP.dll native\%PLATFORM%
COPY %SOLUTION_DIR%\%PLATFORM%\%CONFIGURATION%\TRN4JAVA.dll native\%PLATFORM%
