/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Recording_Scheduling */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Recording_Scheduling
#define _Included_TRN4JAVA_Extended_Simulation_Recording_Scheduling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Recording_Scheduling
 * Method:    configure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Recording_00024Scheduling_configure
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
