/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simplified_Simulation */

#ifndef _Included_TRN4JAVA_Simplified_Simulation
#define _Included_TRN4JAVA_Simplified_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simplified_Simulation
 * Method:    compute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simplified_00024Simulation_compute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
