/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Recording_Weights */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Recording_Weights
#define _Included_TRN4JAVA_Advanced_Simulation_Recording_Weights
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Recording_Weights
 * Method:    configure
 * Signature: (JLTRN4JAVA/Callbacks/Simulation/Recording/Weights;ZZ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Recording_00024Weights_configure
  (JNIEnv *, jclass, jlong, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
