/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Uniform */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Uniform
#define _Included_TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Uniform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Uniform
 * Method:    configure
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Reservoir_00024Weights_00024Feedforward_00024Uniform_configure
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
