/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended */

#ifndef _Included_TRN4JAVA_Extended
#define _Included_TRN4JAVA_Extended
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
