/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Recording_Performances */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Recording_Performances
#define _Included_TRN4JAVA_Advanced_Simulation_Recording_Performances
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Recording_Performances
 * Method:    configure
 * Signature: (JLTRN4JAVA/Callbacks/Simulation/Recording/Performances;ZZZ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Recording_00024Performances_configure
  (JNIEnv *, jclass, jlong, jobject, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
