/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Decoder_Kernel_Model */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Decoder_Kernel_Model
#define _Included_TRN4JAVA_Extended_Simulation_Decoder_Kernel_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Decoder_Kernel_Model
 * Method:    configure
 * Signature: (JJJJJFFFFFFFFJ[F[F[F)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Decoder_00024Kernel_00024Model_configure
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
