/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Reservoir_Weights_Readout */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Reservoir_Weights_Readout
#define _Included_TRN4JAVA_Extended_Simulation_Reservoir_Weights_Readout
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
