/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Measurement_Position_Raw */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Measurement_Position_Raw
#define _Included_TRN4JAVA_Extended_Simulation_Measurement_Position_Raw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Measurement_Position_Raw
 * Method:    configure
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Measurement_00024Position_00024Raw_configure
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
