/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Api_Performances */

#ifndef _Included_TRN4JAVA_Api_Performances
#define _Included_TRN4JAVA_Api_Performances
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
