/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Encoder */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Encoder
#define _Included_TRN4JAVA_Custom_Simulation_Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Encoder
 * Method:    notify
 * Signature: (JJ[F[FJJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Encoder_notify
  (JNIEnv *, jobject, jlong, jlong, jfloatArray, jfloatArray, jlong, jlong);

/*
 * Class:     TRN4JAVA_Custom_Simulation_Encoder
 * Method:    install
 * Signature: (LTRN4JAVA/Custom/Simulation/Encoder;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Encoder_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
