/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Measurement */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Measurement
#define _Included_TRN4JAVA_Extended_Simulation_Measurement
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
