/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simulation_Reservoir_Weights_Feedforward */

#ifndef _Included_TRN4JAVA_Simulation_Reservoir_Weights_Feedforward
#define _Included_TRN4JAVA_Simulation_Reservoir_Weights_Feedforward
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simulation_Reservoir_Weights_Feedforward
 * Method:    install
 * Signature: (LTRN4JAVA/Simulation/Reservoir/Weights;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Reservoir_00024Weights_00024Feedforward_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
