/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Callbacks_Simulation_Measurement_Position_Raw */

#ifndef _Included_TRN4JAVA_Callbacks_Simulation_Measurement_Position_Raw
#define _Included_TRN4JAVA_Callbacks_Simulation_Measurement_Position_Raw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Callbacks_Simulation_Measurement_Position_Raw
 * Method:    install
 * Signature: (LTRN4JAVA/Callbacks/Simulation/Measurement/Raw;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Callbacks_00024Simulation_00024Measurement_00024Position_00024Raw_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
