/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Measurement_Readout_MeanSquareError */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Measurement_Readout_MeanSquareError
#define _Included_TRN4JAVA_Advanced_Simulation_Measurement_Readout_MeanSquareError
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Measurement_Readout_MeanSquareError
 * Method:    configure
 * Signature: (JJLTRN4JAVA/Callbacks/Simulation/Measurement/Processed;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Measurement_00024Readout_00024MeanSquareError_configure
  (JNIEnv *, jclass, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
