/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Scheduler */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Scheduler
#define _Included_TRN4JAVA_Custom_Simulation_Scheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Scheduler
 * Method:    notify
 * Signature: (JJ[I[I)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Scheduler_notify
  (JNIEnv *, jobject, jlong, jlong, jintArray, jintArray);

/*
 * Class:     TRN4JAVA_Custom_Simulation_Scheduler
 * Method:    install
 * Signature: (LTRN4JAVA/Custom/Simulation/Scheduler;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Scheduler_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
