/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Engine_Backend_Local */

#ifndef _Included_TRN4JAVA_Basic_Engine_Backend_Local
#define _Included_TRN4JAVA_Basic_Engine_Backend_Local
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Basic_Engine_Backend_Local
 * Method:    initialize
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Basic_00024Engine_00024Backend_00024Local_initialize
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
