/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Logging */

#ifndef _Included_TRN4JAVA_Basic_Logging
#define _Included_TRN4JAVA_Basic_Logging
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
