/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Scheduler_Snippets */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Scheduler_Snippets
#define _Included_TRN4JAVA_Extended_Simulation_Scheduler_Snippets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Scheduler_Snippets
 * Method:    configure
 * Signature: (JJIIFFFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Scheduler_00024Snippets_configure
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat, jfloat, jfloat, jfloat, jstring);

#ifdef __cplusplus
}
#endif
#endif
