/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Api_Initializer */

#ifndef _Included_TRN4JAVA_Api_Initializer
#define _Included_TRN4JAVA_Api_Initializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Api_Initializer
 * Method:    notify
 * Signature: (I[FIII)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Api_00024Initializer_notify
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
