/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simplified_Plugin */

#ifndef _Included_TRN4JAVA_Simplified_Plugin
#define _Included_TRN4JAVA_Simplified_Plugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simplified_Plugin
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simplified_00024Plugin_initialize
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
