/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Custom */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Custom
#define _Included_TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Custom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Reservoir_Weights_Feedforward_Custom
 * Method:    configure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Reservoir_00024Weights_00024Feedforward_00024Custom_configure
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
