/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Engine_Backend_Remote */

#ifndef _Included_TRN4JAVA_Basic_Engine_Backend_Remote
#define _Included_TRN4JAVA_Basic_Engine_Backend_Remote
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Basic_Engine_Backend_Remote
 * Method:    initialize
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Basic_00024Engine_00024Backend_00024Remote_initialize
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
