/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Recording_Weights */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Recording_Weights
#define _Included_TRN4JAVA_Extended_Simulation_Recording_Weights
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Recording_Weights
 * Method:    configure
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Recording_00024Weights_configure
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
