/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Reservoir_Weights */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Reservoir_Weights
#define _Included_TRN4JAVA_Custom_Simulation_Reservoir_Weights
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Reservoir_Weights
 * Method:    notify
 * Signature: (J[FJJJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Reservoir_00024Weights_notify
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
