/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Engine_Events_Configured */

#ifndef _Included_TRN4JAVA_Advanced_Engine_Events_Configured
#define _Included_TRN4JAVA_Advanced_Engine_Events_Configured
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Engine_Events_Configured
 * Method:    install
 * Signature: (LTRN4JAVA/Advanced/Engine/Events/Configured;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Engine_00024Events_00024Configured_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
