/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Api_Association */

#ifndef _Included_TRN4JAVA_Api_Association
#define _Included_TRN4JAVA_Api_Association
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
