/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Api_Loop */

#ifndef _Included_TRN4JAVA_Api_Loop
#define _Included_TRN4JAVA_Api_Loop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Api_Loop
 * Method:    notify
 * Signature: (I[FII)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Api_00024Loop_notify
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
