/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Engine_Events */

#ifndef _Included_TRN4JAVA_Advanced_Engine_Events
#define _Included_TRN4JAVA_Advanced_Engine_Events
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
