/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Loop_SpatialFilter */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Loop_SpatialFilter
#define _Included_TRN4JAVA_Advanced_Simulation_Loop_SpatialFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Loop_SpatialFilter
 * Method:    configure
 * Signature: (JJJJLTRN4JAVA/Custom/Simulation/Loop;LTRN4JAVA/Custom/Simulation/Loop;JJFFFF[FFFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Loop_00024SpatialFilter_configure
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jobject, jobject, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloatArray, jfloat, jfloat, jfloat, jstring);

#ifdef __cplusplus
}
#endif
#endif
