/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Engine_Backend_Distributed */

#ifndef _Included_TRN4JAVA_Basic_Engine_Backend_Distributed
#define _Included_TRN4JAVA_Basic_Engine_Backend_Distributed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Basic_Engine_Backend_Distributed
 * Method:    initialize
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Basic_00024Engine_00024Backend_00024Distributed_initialize
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
