/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simulation_Scheduler_Mutator_Custom */

#ifndef _Included_TRN4JAVA_Simulation_Scheduler_Mutator_Custom
#define _Included_TRN4JAVA_Simulation_Scheduler_Mutator_Custom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simulation_Scheduler_Mutator_Custom
 * Method:    configure
 * Signature: (JJLTRN4JAVA/Simulation/Scheduler/Mutator;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Scheduler_00024Mutator_00024Custom_configure
  (JNIEnv *, jclass, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
