/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Engine_Events_Completed */

#ifndef _Included_TRN4JAVA_Engine_Events_Completed
#define _Included_TRN4JAVA_Engine_Events_Completed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Engine_Events_Completed
 * Method:    install
 * Signature: (LTRN4JAVA/Engine/Events/Completed;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Engine_00024Events_00024Completed_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
