/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Reverse */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Reverse
#define _Included_TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Reverse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Reverse
 * Method:    configure
 * Signature: (JJFJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Scheduler_00024Mutator_00024Reverse_configure
  (JNIEnv *, jclass, jlong, jlong, jfloat, jlong);

#ifdef __cplusplus
}
#endif
#endif
