/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Scheduler_Custom */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Scheduler_Custom
#define _Included_TRN4JAVA_Extended_Simulation_Scheduler_Custom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Scheduler_Custom
 * Method:    configure
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Scheduler_00024Custom_configure
  (JNIEnv *, jclass, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
