/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Reservoir_Weights_Feedforward */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Reservoir_Weights_Feedforward
#define _Included_TRN4JAVA_Advanced_Simulation_Reservoir_Weights_Feedforward
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
