/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Engine */

#ifndef _Included_TRN4JAVA_Basic_Engine
#define _Included_TRN4JAVA_Basic_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Basic_Engine
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Basic_00024Engine_initialize
  (JNIEnv *, jclass);

/*
 * Class:     TRN4JAVA_Basic_Engine
 * Method:    uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Basic_00024Engine_uninitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
