/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Simulation */

#ifndef _Included_TRN4JAVA_Basic_Simulation
#define _Included_TRN4JAVA_Basic_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Basic_Simulation
 * Method:    encode
 * Signature: (LTRN4JAVA/Basic/Simulation/Identifier;)J
 */
JNIEXPORT jlong JNICALL Java_TRN4JAVA_Basic_00024Simulation_encode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     TRN4JAVA_Basic_Simulation
 * Method:    decode
 * Signature: (J)LTRN4JAVA/Basic/Simulation/Identifier;
 */
JNIEXPORT jobject JNICALL Java_TRN4JAVA_Basic_00024Simulation_decode
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
