/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom */

#ifndef _Included_TRN4JAVA_Custom
#define _Included_TRN4JAVA_Custom
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
