/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Engine_Execution */

#ifndef _Included_TRN4JAVA_Extended_Engine_Execution
#define _Included_TRN4JAVA_Extended_Engine_Execution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Engine_Execution
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Engine_00024Execution_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
