/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Api_Scheduler */

#ifndef _Included_TRN4JAVA_Api_Scheduler
#define _Included_TRN4JAVA_Api_Scheduler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Api_Scheduler
 * Method:    notify
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Api_00024Scheduler_notify
  (JNIEnv *, jobject, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
