/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation */

#ifndef _Included_TRN4JAVA_Custom_Simulation
#define _Included_TRN4JAVA_Custom_Simulation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
