/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Loop_Stimulus */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Loop_Stimulus
#define _Included_TRN4JAVA_Custom_Simulation_Loop_Stimulus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Loop_Stimulus
 * Method:    install
 * Signature: (LTRN4JAVA/Custom/Simulation/Loop;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Loop_00024Stimulus_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
