/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Decoder_Linear */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Decoder_Linear
#define _Included_TRN4JAVA_Extended_Simulation_Decoder_Linear
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Decoder_Linear
 * Method:    configure
 * Signature: (JJJ[F[F)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Decoder_00024Linear_configure
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
