/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Recording */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Recording
#define _Included_TRN4JAVA_Extended_Simulation_Recording
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
