/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Engine */

#ifndef _Included_TRN4JAVA_Extended_Engine
#define _Included_TRN4JAVA_Extended_Engine
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
