/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simulation_Recording_Performances */

#ifndef _Included_TRN4JAVA_Simulation_Recording_Performances
#define _Included_TRN4JAVA_Simulation_Recording_Performances
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simulation_Recording_Performances
 * Method:    install
 * Signature: (LTRN4JAVA/Simulation/Recording/Performances;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Recording_00024Performances_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
