/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Encoder_Custom */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Encoder_Custom
#define _Included_TRN4JAVA_Advanced_Simulation_Encoder_Custom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Encoder_Custom
 * Method:    configure
 * Signature: (JJJLTRN4JAVA/Custom/Simulation/Encoder;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Encoder_00024Custom_configure
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
