/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simulation_Recording_Weights */

#ifndef _Included_TRN4JAVA_Simulation_Recording_Weights
#define _Included_TRN4JAVA_Simulation_Recording_Weights
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simulation_Recording_Weights
 * Method:    install
 * Signature: (LTRN4JAVA/Simulation/Recording/Weights;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Recording_00024Weights_install
  (JNIEnv *, jclass, jobject);

/*
 * Class:     TRN4JAVA_Simulation_Recording_Weights
 * Method:    configure
 * Signature: (JLTRN4JAVA/Simulation/Recording/Weights;ZZ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Recording_00024Weights_configure
  (JNIEnv *, jclass, jlong, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
