/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Loop */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Loop
#define _Included_TRN4JAVA_Custom_Simulation_Loop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Loop
 * Method:    notify
 * Signature: (JJ[FJJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Loop_notify
  (JNIEnv *, jobject, jlong, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     TRN4JAVA_Custom_Simulation_Loop
 * Method:    install
 * Signature: (LTRN4JAVA/Custom/Simulation/Loop;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Loop_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
