/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Simulation_Recording_Scheduling */

#ifndef _Included_TRN4JAVA_Simulation_Recording_Scheduling
#define _Included_TRN4JAVA_Simulation_Recording_Scheduling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Simulation_Recording_Scheduling
 * Method:    install
 * Signature: (LTRN4JAVA/Simulation/Recording/Scheduling;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Recording_00024Scheduling_install
  (JNIEnv *, jclass, jobject);

/*
 * Class:     TRN4JAVA_Simulation_Recording_Scheduling
 * Method:    configure
 * Signature: (JLTRN4JAVA/Simulation/Recording/Scheduling;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Simulation_00024Recording_00024Scheduling_configure
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
