/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Loop_Custom */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Loop_Custom
#define _Included_TRN4JAVA_Extended_Simulation_Loop_Custom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Loop_Custom
 * Method:    configure
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Loop_00024Custom_configure
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
