/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Reservoir_WidrowHoff */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Reservoir_WidrowHoff
#define _Included_TRN4JAVA_Extended_Simulation_Reservoir_WidrowHoff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Reservoir_WidrowHoff
 * Method:    configure
 * Signature: (JJJJFFFJJJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Reservoir_00024WidrowHoff_configure
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jfloat, jfloat, jfloat, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
