/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Shuffle */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Shuffle
#define _Included_TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Shuffle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Scheduler_Mutator_Shuffle
 * Method:    configure
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Scheduler_00024Mutator_00024Shuffle_configure
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
