/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Measurement_Readout_FrechetDistance */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Measurement_Readout_FrechetDistance
#define _Included_TRN4JAVA_Advanced_Simulation_Measurement_Readout_FrechetDistance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Measurement_Readout_FrechetDistance
 * Method:    configure
 * Signature: (JJLTRN4JAVA/Callbacks/Simulation/Measurement/Processed;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Measurement_00024Readout_00024FrechetDistance_configure
  (JNIEnv *, jclass, jlong, jlong, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
