/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation_Scheduler_Tiled */

#ifndef _Included_TRN4JAVA_Extended_Simulation_Scheduler_Tiled
#define _Included_TRN4JAVA_Extended_Simulation_Scheduler_Tiled
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation_Scheduler_Tiled
 * Method:    configure
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_00024Scheduler_00024Tiled_configure
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
