/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Scheduler_Mutator */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Scheduler_Mutator
#define _Included_TRN4JAVA_Custom_Simulation_Scheduler_Mutator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Scheduler_Mutator
 * Method:    notify
 * Signature: (JJ[I[I)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Scheduler_00024Mutator_notify
  (JNIEnv *, jobject, jlong, jlong, jintArray, jintArray);

/*
 * Class:     TRN4JAVA_Custom_Simulation_Scheduler_Mutator
 * Method:    install
 * Signature: (LTRN4JAVA/Custom/Simulation/Scheduler/Mutator;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Scheduler_00024Mutator_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
