/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Custom_Simulation_Reservoir_Recurrent */

#ifndef _Included_TRN4JAVA_Custom_Simulation_Reservoir_Recurrent
#define _Included_TRN4JAVA_Custom_Simulation_Reservoir_Recurrent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Custom_Simulation_Reservoir_Recurrent
 * Method:    install
 * Signature: (LTRN4JAVA/Custom/Simulation/Reservoir/Weights;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Custom_00024Simulation_00024Reservoir_00024Recurrent_install
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
