/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Extended_Simulation */

#ifndef _Included_TRN4JAVA_Extended_Simulation
#define _Included_TRN4JAVA_Extended_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    allocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_allocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    train
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_train
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jstring);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    test
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IZI)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_test
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jstring, jint, jboolean, jint);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    declare_sequence
 * Signature: (JLjava/lang/String;Ljava/lang/String;[FJ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_declare_1sequence
  (JNIEnv *, jclass, jlong, jstring, jstring, jfloatArray, jlong);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    declare_set
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_declare_1set
  (JNIEnv *, jclass, jlong, jstring, jstring, jobjectArray);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    configure_begin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_configure_1begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     TRN4JAVA_Extended_Simulation
 * Method:    configure_end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Extended_00024Simulation_configure_1end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
