/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Advanced_Simulation_Recording_States */

#ifndef _Included_TRN4JAVA_Advanced_Simulation_Recording_States
#define _Included_TRN4JAVA_Advanced_Simulation_Recording_States
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Advanced_Simulation_Recording_States
 * Method:    configure
 * Signature: (JLTRN4JAVA/Callbacks/Simulation/Recording/States;ZZZ)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Advanced_00024Simulation_00024Recording_00024States_configure
  (JNIEnv *, jclass, jlong, jobject, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
