/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Callbacks_Simulation_Measurement_Raw */

#ifndef _Included_TRN4JAVA_Callbacks_Simulation_Measurement_Raw
#define _Included_TRN4JAVA_Callbacks_Simulation_Measurement_Raw
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
