/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Basic_Logging_Severity_Error */

#ifndef _Included_TRN4JAVA_Basic_Logging_Severity_Error
#define _Included_TRN4JAVA_Basic_Logging_Severity_Error
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Basic_Logging_Severity_Error
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Basic_00024Logging_00024Severity_00024Error_setup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
