/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4JAVA_Sequences */

#ifndef _Included_TRN4JAVA_Sequences
#define _Included_TRN4JAVA_Sequences
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4JAVA_Sequences
 * Method:    declare
 * Signature: (Ljava/lang/String;[FJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TRN4JAVA_Sequences_declare
  (JNIEnv *, jclass, jstring, jfloatArray, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
