/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TRN4SCS_Sequences */

#ifndef _Included_TRN4SCS_Sequences
#define _Included_TRN4SCS_Sequences
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TRN4SCS_Sequences
 * Method:    declare
 * Signature: (Ljava/lang/String;Ljava/lang/String;[FJ)V
 */
JNIEXPORT void JNICALL Java_TRN4SCS_Sequences_declare
  (JNIEnv *, jclass, jstring, jstring, jfloatArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
