#pragma once
#ifdef USE_VLD
#include <vld.h>
#endif 
#include <functional>
#include <tuple>
#include <string>
#include <vector>
#include <list>
#include <queue>
#include <future>
#include <iostream>
#include <memory>
#include <boost/signals2.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/bind.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/enable_shared_from_this.hpp>
#include <boost/asio.hpp>
#include <boost/asio/deadline_timer.hpp>